@emediceBE_HostAddress = http://localhost:5001

GET {{emediceBE_HostAddress}}/api/users
Content-Type: application/json

###

POST {{emediceBE_HostAddress}}/api/users/registration
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "securepassword"
}
